apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: no37y1ved-go 
  janus-idp.io/tekton: no37y1ved-go
  backstage.io/kubernetes-id: no37y1ved-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: no37y1ved-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml