apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: no37y1ved-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: no37y1ved-go 
  name: no37y1ved-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: no37y1ved-go
    weight: 100 
